# Generated by Django 5.1.4 on 2024-12-10 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBannerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_media', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='news_media/image_banner_media/', verbose_name='Image Banner media')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
            },
        ),
        migrations.CreateModel(
            name='ImageBannerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_news', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='news_media/image_banner_news/', verbose_name='Image Banner news')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='media title')),
                ('media_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='media title')),
                ('media_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='media title')),
                ('media_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='media description')),
                ('media_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='media description')),
                ('media_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='media description')),
                ('media_image', models.ImageField(upload_to='news_media/media_image/', verbose_name='media image')),
                ('image_banner_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Media.imagebannermedia')),
            ],
            options={
                'verbose_name': 'Media Card',
                'verbose_name_plural': 'Media Cards',
            },
        ),
        migrations.CreateModel(
            name='MediaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_inside_page', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='news_media/image_banner/', verbose_name='image banner inside page')),
                ('media_page_video', models.FileField(blank=True, help_text='Optional', null=True, upload_to='news_media/videos_page/', verbose_name='video')),
                ('media_page_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='media page title')),
                ('media_page_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='media page title')),
                ('media_page_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='media page title')),
                ('media_page_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='media page description')),
                ('media_page_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='media page description')),
                ('media_page_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='media page description')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('image_banner_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newmedia', to='News_Media.imagebannermedia')),
                ('media', models.OneToOneField(help_text='If you add Media Card, you must save and continue editing before typing any entry for it to appear in the drop-down list.', on_delete=django.db.models.deletion.CASCADE, to='News_Media.media')),
            ],
            options={
                'verbose_name': 'Media Details',
                'verbose_name_plural': 'Media Details',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='news title')),
                ('news_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='news title')),
                ('news_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='news title')),
                ('news_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='news description')),
                ('news_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='news description')),
                ('news_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='news description')),
                ('news_date', models.DateField(default=django.utils.timezone.now)),
                ('news_image', models.ImageField(upload_to='news_media/news_image/', verbose_name='news image')),
                ('image_banner_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Media.imagebannernews')),
            ],
            options={
                'verbose_name': 'News Card',
                'verbose_name_plural': 'News Cards',
            },
        ),
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_inside_page', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='news_media/image_banner/', verbose_name='image banner inside page')),
                ('news_page_image', models.ImageField(upload_to='news_media/news_page_image/', verbose_name='news page image')),
                ('news_page_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='news page title')),
                ('news_page_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='news page title')),
                ('news_page_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='news page title')),
                ('news_page_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='news page description')),
                ('news_page_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='news page description')),
                ('news_page_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='news page description')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('image_banner_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new', to='News_Media.imagebannernews')),
                ('news', models.OneToOneField(help_text='If you add News Card, you must save and continue editing before typing any entry for it to appear in the drop-down list.', on_delete=django.db.models.deletion.CASCADE, to='News_Media.news')),
            ],
            options={
                'verbose_name': 'News Details',
                'verbose_name_plural': 'News Details',
            },
        ),
    ]
