# Generated by Django 5.1.4 on 2024-12-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Banner_Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_tender', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='tenders/image_banner_tender/', verbose_name='Image Banner Tender')),
            ],
            options={
                'verbose_name': 'Tenders',
                'verbose_name_plural': 'Tenders',
            },
        ),
        migrations.CreateModel(
            name='TenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Tender Title')),
                ('tender_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Tender Title')),
                ('tender_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Tender Title')),
                ('tender_image_or_icon', models.ImageField(help_text='For icons, visit <a href="https://www.flaticon.com/" target="_blank">https://www.flaticon.com/</a>', upload_to='Tenders/tender_image_or_icon/', verbose_name='Tender Image or Icon')),
                ('image_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Tenders.image_banner_tender')),
            ],
            options={
                'verbose_name': 'Tenders',
                'verbose_name_plural': 'Tenders',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Category Title')),
                ('category_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Category Title')),
                ('category_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Category Title')),
                ('category_pdf_file', models.FileField(upload_to='Tenders/PDF/', verbose_name='Category PDF File')),
                ('category_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='Category Description')),
                ('category_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='Category Description')),
                ('category_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='Category Description')),
                ('image_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenders.image_banner_tender')),
                ('category', models.ForeignKey(help_text='Here you can choose more than one tender; you must save and continue editing for it to appear.', on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='Tenders.tendercategory')),
            ],
            options={
                'verbose_name': 'Tender Category',
                'verbose_name_plural': 'Tender Categories',
            },
        ),
    ]
