# Generated by Django 5.1.4 on 2024-12-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBannerInnovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_innovation', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='innovation/image_banner_innovation/', verbose_name='Image Banner innovation')),
            ],
            options={
                'verbose_name': 'Innovation & Expansion',
                'verbose_name_plural': ' Innovation & Expansion',
            },
        ),
        migrations.CreateModel(
            name='InnovationExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_image', models.ImageField(upload_to='innovation/innovation_card_image/', verbose_name='innovation_image')),
                ('innovation_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='innovation title')),
                ('innovation_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='innovation title')),
                ('innovation_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='innovation title')),
                ('innovation_description', models.TextField(help_text='Maximum 1000 characters', max_length=1000, verbose_name='innovation description')),
                ('innovation_description_en', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='innovation description')),
                ('innovation_description_ar', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='innovation description')),
                ('image_banner_innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Innovation_Expansion.imagebannerinnovation')),
            ],
            options={
                'verbose_name': 'Innovation_Expansion',
                'verbose_name_plural': 'Innovation_Expansion',
            },
        ),
        migrations.CreateModel(
            name='InnovationMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_inside_page', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='innovation/image_banner/', verbose_name='image banner inside page')),
                ('detsils_innovation_image', models.ImageField(upload_to='innovation/detsils_innovation_image/', verbose_name='detsils innovation image')),
                ('detsils_innovation_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='detsils innovation title')),
                ('detsils_innovation_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='detsils innovation title')),
                ('detsils_innovation_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='detsils innovation title')),
                ('detsils_innovation_description', models.TextField(help_text='Maximum 1000 characters', max_length=1000, verbose_name='detsils innovation description')),
                ('detsils_innovation_description_en', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='detsils innovation description')),
                ('detsils_innovation_description_ar', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='detsils innovation description')),
                ('video', models.FileField(blank=True, help_text='Optional', null=True, upload_to='innovation/videos_page/', verbose_name='video')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('ImageBannerInnovation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innovation', to='Innovation_Expansion.imagebannerinnovation')),
                ('innovationexpansion', models.OneToOneField(help_text='If you add Innovation & Expansion, you must save and continue editing before typing any entry for it to appear in the drop-down list.', on_delete=django.db.models.deletion.CASCADE, related_name='innovation', to='Innovation_Expansion.innovationexpansion')),
            ],
            options={
                'verbose_name': 'Innovation_inside_Page',
                'verbose_name_plural': 'Innovation_inside_Page',
            },
        ),
    ]
