# Generated by Django 5.1.4 on 2024-12-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='about_us/image_banner/', verbose_name='image banner')),
                ('video', models.FileField(blank=True, null=True, upload_to='about_us/videos_page/', verbose_name='video')),
                ('image', models.ImageField(upload_to='about_us/image_page/', verbose_name='image')),
                ('Years_Of_Experienced', models.IntegerField(verbose_name='Years Of Experience')),
                ('description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='description')),
                ('description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='description')),
                ('description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Image_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='about_us/Board_Member_image/', verbose_name='image banner')),
            ],
            options={
                'verbose_name': 'Board Of Directors',
                'verbose_name_plural': 'Board Of Directors',
            },
        ),
        migrations.CreateModel(
            name='Image_Banner_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_brand', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='about_us/Image_Banner_Brand/', verbose_name='image banner_brand')),
            ],
            options={
                'verbose_name': 'Our Brand',
                'verbose_name_plural': 'Our Brand',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_card', models.ImageField(upload_to='about_us/image_card/', verbose_name='Image Card')),
                ('title_card', models.CharField(help_text='Maximum 50 characters', max_length=50, verbose_name='title card')),
                ('title_card_en', models.CharField(help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='title card')),
                ('title_card_ar', models.CharField(help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='title card')),
                ('description_card', models.TextField(help_text='Maximum 100 characters', max_length=100, verbose_name='description')),
                ('description_card_en', models.TextField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='description')),
                ('description_card_ar', models.TextField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='description')),
                ('is_collapsible', models.BooleanField(default=False, verbose_name='Is Collapsible')),
                ('collapse_description', models.TextField(blank=True, help_text='Maximum 300 characters', max_length=300, null=True, verbose_name='Collapse Description')),
                ('collapse_description_en', models.TextField(blank=True, help_text='Maximum 300 characters', max_length=300, null=True, verbose_name='Collapse Description')),
                ('collapse_description_ar', models.TextField(blank=True, help_text='Maximum 300 characters', max_length=300, null=True, verbose_name='Collapse Description')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_cards', to='Dmsco.about_us')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Person name')),
                ('person_name_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Person name')),
                ('person_name_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Person name')),
                ('person_position', models.CharField(help_text='Maximum 150 characters', max_length=150, verbose_name='person position')),
                ('person_position_en', models.CharField(help_text='Maximum 150 characters', max_length=150, null=True, verbose_name='person position')),
                ('person_position_ar', models.CharField(help_text='Maximum 150 characters', max_length=150, null=True, verbose_name='person position')),
                ('person_image', models.ImageField(help_text="It's better to put a blank image", upload_to='about_us/Board_Of_Directors_image', verbose_name='person image')),
                ('image_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_image', to='Dmsco.image_banner')),
            ],
            options={
                'verbose_name': 'Board Of Directors',
                'verbose_name_plural': 'Board Of Directors',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Maximum 20 characters', max_length=20, verbose_name='brand name')),
                ('brand_name_en', models.CharField(help_text='Maximum 20 characters', max_length=20, null=True, verbose_name='brand name')),
                ('brand_name_ar', models.CharField(help_text='Maximum 20 characters', max_length=20, null=True, verbose_name='brand name')),
                ('brand_image', models.ImageField(upload_to='about_us/brands_images/', verbose_name='brand image')),
                ('image_banner_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_image', to='Dmsco.image_banner_brand')),
            ],
            options={
                'verbose_name': 'Brands',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
