# Generated by Django 5.1.4 on 2024-12-10 00:00

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlDawaaDepartmentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Department Title')),
                ('department_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Department Title')),
                ('department_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Department Title')),
                ('department_image_or_icon', models.ImageField(help_text='To select icons of specific sizes, please visit this site. For icons, visit <a href="https://www.flaticon.com/" target="_blank">Flaticon</a>.', upload_to='we_ALdawaa/image_or_icon/', verbose_name='Department Image or Icon')),
                ('department_description', models.TextField(help_text='Maximum 1000 characters', max_length=1000, verbose_name='Department Description')),
                ('department_description_en', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='Department Description')),
                ('department_description_ar', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='Department Description')),
                ('department_bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Background Color')),
                ('department_text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Text Color')),
            ],
            options={
                'verbose_name': 'Al Dawaa Department Card',
                'verbose_name_plural': 'Al Dawaa Department Card',
            },
        ),
        migrations.CreateModel(
            name='Image_Banner_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_program', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='we_aldawaa/Image_Banner_Program/', verbose_name='image banner program')),
            ],
            options={
                'verbose_name': 'Our Program',
                'verbose_name_plural': 'Our Programs',
            },
        ),
        migrations.CreateModel(
            name='ImageBannerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_department', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='we_aldawaa/image_banner_department/', verbose_name='Image Banner Department')),
            ],
            options={
                'verbose_name': 'AL Dawaa Department',
                'verbose_name_plural': 'AL Dawaa Department',
            },
        ),
        migrations.CreateModel(
            name='Social_Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='we_ALdawaa/Social_Responsibility_Banner/', verbose_name='image banner')),
                ('page_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='page title')),
                ('page_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='page title')),
                ('page_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='page title')),
                ('page_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='page description')),
                ('page_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='page description')),
                ('page_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='page description')),
            ],
            options={
                'verbose_name': 'Social_Page_Responsibility',
                'verbose_name_plural': 'Social_Page_Responsibility',
            },
        ),
        migrations.CreateModel(
            name='We_Aldawaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='we_aldawaa/image_banner/', verbose_name='image banner')),
                ('section_image', models.ImageField(upload_to='we_aldawaa/section_image/', verbose_name='section image')),
                ('section_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='section title')),
                ('section_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='section title')),
                ('section_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='section title')),
                ('section_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='section description')),
                ('section_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='section description')),
                ('section_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='section description')),
            ],
            options={
                'verbose_name': 'We_Aldawaa',
                'verbose_name_plural': 'We_Aldawaa',
            },
        ),
        migrations.CreateModel(
            name='Department_Inside_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_inside_page', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='we_aldawaa/banner_Department_Inside_Page/', verbose_name='image banner')),
                ('section_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Section Title')),
                ('section_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Section Title')),
                ('section_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Section Title')),
                ('section_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='Section Description')),
                ('section_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='Section Description')),
                ('section_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='Section Description')),
                ('section_image', models.ImageField(upload_to='we_aldawaa/section_image_Department_Inside_Page/', verbose_name='Section Image')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('category', models.OneToOneField(help_text='If you add a Al Dawaa Department Card, you must save and continue editing before typing any entry for it to appear in the drop-down list.', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='Al_Dawaa.aldawaadepartmentcard')),
                ('ImageBannerDepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Al_Dawaa.imagebannerdepartment')),
            ],
            options={
                'verbose_name': 'Department Inside Page',
                'verbose_name_plural': 'Department Inside Page',
            },
        ),
        migrations.AddField(
            model_name='aldawaadepartmentcard',
            name='image_banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Al_Dawaa.imagebannerdepartment'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_image_or_icon', models.ImageField(help_text='To select icons of specific sizes, please visit this site. For icons, visit <a href="https://www.flaticon.com/" target="_blank">Flaticon</a>.', upload_to='we_aldawaa/program_image_or_icon/', verbose_name='program image or icon')),
                ('program_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='program title')),
                ('program_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='program title')),
                ('program_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='program title')),
                ('program_description', models.TextField(help_text='Maximum 1000 characters', max_length=1000, verbose_name='program description')),
                ('program_description_en', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='program description')),
                ('program_description_ar', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='program description')),
                ('image_banner_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_image', to='Al_Dawaa.image_banner_program')),
            ],
            options={
                'verbose_name': 'Our Program',
                'verbose_name_plural': 'Our Programs',
            },
        ),
        migrations.CreateModel(
            name='Card_Social_Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='card title')),
                ('card_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='card title')),
                ('card_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='card title')),
                ('card_image', models.ImageField(upload_to='we_aldawaa/Social_Responsibility_card_image/', verbose_name='section image')),
                ('card_description', models.TextField(help_text='Maximum 2000 characters', max_length=2000, verbose_name='section description')),
                ('card_description_en', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='section description')),
                ('card_description_ar', models.TextField(help_text='Maximum 2000 characters', max_length=2000, null=True, verbose_name='section description')),
                ('image_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Al_Dawaa.social_responsibility')),
            ],
            options={
                'verbose_name': 'Social_Responsibility',
                'verbose_name_plural': 'Social_Responsibility',
            },
        ),
        migrations.CreateModel(
            name='Social_Responsibility_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_inside_page', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='we_aldawaa/Social_Responsibility_Banner/', verbose_name='image banner')),
                ('title_details_social', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='title details social')),
                ('title_details_social_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='title details social')),
                ('title_details_social_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='title details social')),
                ('image_details_social', models.ImageField(upload_to='Social_Responsibility/image_details_social/', verbose_name='image details social')),
                ('description_details_social', models.TextField(help_text='Maximum 1000 characters', max_length=1000, verbose_name='description details social')),
                ('description_details_social_en', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='description details social')),
                ('description_details_social_ar', models.TextField(help_text='Maximum 1000 characters', max_length=1000, null=True, verbose_name='description details social')),
                ('link', models.URLField(blank=True, help_text='optional', null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('Card_Social_Responsibility', models.OneToOneField(help_text='If you add a social responsibility card, you must save and continue editing before typing any entry for it to appear in the drop-down lis', on_delete=django.db.models.deletion.CASCADE, related_name='social_responsibility_details', to='Al_Dawaa.card_social_responsibility')),
                ('image_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Al_Dawaa.social_responsibility')),
            ],
            options={
                'verbose_name': 'Social_Responsibility_details',
                'verbose_name_plural': 'Social_Responsibility_details',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_line_year', models.PositiveIntegerField(verbose_name='Time line year')),
                ('Time_line_description', models.TextField(help_text='Maximum 100 characters', max_length=100, verbose_name='Time line description')),
                ('Time_line_description_en', models.TextField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Time line description')),
                ('Time_line_description_ar', models.TextField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Time line description')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_timeline', to='Al_Dawaa.we_aldawaa')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='feature title')),
                ('feature_title_en', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='feature title')),
                ('feature_title_ar', models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='feature title')),
                ('feature_count', models.PositiveIntegerField(verbose_name='feature count')),
                ('feature_image_or_icon', models.ImageField(help_text='For icons, visit <a href="https://www.flaticon.com/" target="_blank">https://www.flaticon.com/</a>', upload_to='we_aldawaa/feature_image_or_icon', verbose_name='feature image or icon')),
                ('we_aldawaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_icon', to='Al_Dawaa.we_aldawaa')),
            ],
        ),
    ]
